CREATE OR REPLACE PACKAGE ADMINFILMFUNCTIONS AS
    PROCEDURE ADD_COMMENT(
        USER_REVIEW_TEXT IN USERS_REVIEWS_ON_MOVIE.USER_REVIEW_TEXT%TYPE,
        DATE_OF_REVIEW IN USERS_REVIEWS_ON_MOVIE.DATE_OF_REVIEW%TYPE,
        USER_PROFILE_ID IN USERS_REVIEWS_ON_MOVIE.USER_PROFILE_ID%TYPE,
        ALL_INFORMATION_ABOUT_FILM_ID IN USERS_REVIEWS_ON_MOVIE.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    );
    PROCEDURE DELETE_COMMENT(
        COMMENT_ID IN USERS_REVIEWS_ON_MOVIE.USERS_REVIEWS_ON_MOVIE_ID%TYPE
    );
    PROCEDURE ADD_FILM(
        TITLE IN ALL_INFORMATION_ABOUT_FILM.TITLE%TYPE,
        ORIGINAL_TITLE IN ALL_INFORMATION_ABOUT_FILM.ORIGINAL_TITLE%TYPE,
        POSTER IN ALL_INFORMATION_ABOUT_FILM.POSTER%TYPE,
        YEAR_OF_POSTING IN ALL_INFORMATION_ABOUT_FILM.YEAR_OF_POSTING%TYPE,
        COUNTRY IN ALL_INFORMATION_ABOUT_FILM.COUNTRY%TYPE,
        DESCRIPTION IN ALL_INFORMATION_ABOUT_FILM.DESCRIPTION%TYPE,
        RATING_IMDb IN ALL_INFORMATION_ABOUT_FILM.RATING_IMDb%TYPE,
        RATING_KP IN ALL_INFORMATION_ABOUT_FILM.RATING_KP%TYPE,
        BOX_OFFICE_RECEIPTS IN ALL_INFORMATION_ABOUT_FILM.BOX_OFFICE_RECEIPTS%TYPE,
        BUDGET IN ALL_INFORMATION_ABOUT_FILM.BUDGET%TYPE,
        AGE IN ALL_INFORMATION_ABOUT_FILM.AGE%TYPE,
        VIEWING_TIME IN ALL_INFORMATION_ABOUT_FILM.VIEWING_TIME%TYPE,
        GENRES IN ALL_INFORMATION_ABOUT_FILM.GENRES%TYPE,
        DIRECTORS IN ALL_INFORMATION_ABOUT_FILM.DIRECTORS%TYPE,
        ACTORS IN ALL_INFORMATION_ABOUT_FILM.ACTORS%TYPE,
        INTERESTING_FACT IN ALL_INFORMATION_ABOUT_FILM.INTERESTING_FACT%TYPE
        );
        
    PROCEDURE DELETE_FILM_BY_ID(
            FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
        );
    
    FUNCTION FIND_BY_ID(
        FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) RETURN SYS_REFCURSOR;
    
    FUNCTION GET_ALL_BY_ID(
        FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) RETURN SYS_REFCURSOR;
    
    PROCEDURE UPDATE_FILM(
        FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE,
        TITLE IN ALL_INFORMATION_ABOUT_FILM.TITLE%TYPE,
        ORIGINAL_TITLE IN ALL_INFORMATION_ABOUT_FILM.ORIGINAL_TITLE%TYPE,
        POSTER IN ALL_INFORMATION_ABOUT_FILM.POSTER%TYPE,
        YEAR_OF_POSTING IN ALL_INFORMATION_ABOUT_FILM.YEAR_OF_POSTING%TYPE,
        COUNTRY IN ALL_INFORMATION_ABOUT_FILM.COUNTRY%TYPE,
        DESCRIPTION IN ALL_INFORMATION_ABOUT_FILM.DESCRIPTION%TYPE,
        RATING_IMDb IN ALL_INFORMATION_ABOUT_FILM.RATING_IMDb%TYPE,
        RATING_KP IN ALL_INFORMATION_ABOUT_FILM.RATING_KP%TYPE,
        BOX_OFFICE_RECEIPTS IN ALL_INFORMATION_ABOUT_FILM.BOX_OFFICE_RECEIPTS%TYPE,
        BUDGET IN ALL_INFORMATION_ABOUT_FILM.BUDGET%TYPE,
        AGE IN ALL_INFORMATION_ABOUT_FILM.AGE%TYPE,
        VIEWING_TIME IN ALL_INFORMATION_ABOUT_FILM.VIEWING_TIME%TYPE,
        GENRES IN ALL_INFORMATION_ABOUT_FILM.GENRES%TYPE,
        DIRECTORS IN ALL_INFORMATION_ABOUT_FILM.DIRECTORS%TYPE,
        ACTORS IN ALL_INFORMATION_ABOUT_FILM.ACTORS%TYPE,
        INTERESTING_FACT IN ALL_INFORMATION_ABOUT_FILM.INTERESTING_FACT%TYPE
        );
    
END ADMINFILMFUNCTIONS;
/

CREATE OR REPLACE PACKAGE BODY ADMINFILMFUNCTIONS AS
    
    PROCEDURE DELETE_COMMENT(
        COMMENT_ID IN USERS_REVIEWS_ON_MOVIE.USERS_REVIEWS_ON_MOVIE_ID%TYPE
    )IS
    BEGIN
        DELETE USERS_REVIEWS_ON_MOVIE 
            WHERE USERS_REVIEWS_ON_MOVIE.USERS_REVIEWS_ON_MOVIE_ID = COMMENT_ID;
        COMMIT;
    END DELETE_COMMENT;

    PROCEDURE ADD_COMMENT(
        USER_REVIEW_TEXT IN USERS_REVIEWS_ON_MOVIE.USER_REVIEW_TEXT%TYPE,
        DATE_OF_REVIEW IN USERS_REVIEWS_ON_MOVIE.DATE_OF_REVIEW%TYPE,
        USER_PROFILE_ID IN USERS_REVIEWS_ON_MOVIE.USER_PROFILE_ID%TYPE,
        ALL_INFORMATION_ABOUT_FILM_ID IN USERS_REVIEWS_ON_MOVIE.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) IS
    BEGIN
        INSERT INTO USERS_REVIEWS_ON_MOVIE VALUES(
            DEFAULT,USER_REVIEW_TEXT,DATE_OF_REVIEW,USER_PROFILE_ID,ALL_INFORMATION_ABOUT_FILM_ID
        );
        COMMIT;
    END ADD_COMMENT;


    PROCEDURE ADD_FILM(
        TITLE IN ALL_INFORMATION_ABOUT_FILM.TITLE%TYPE,
        ORIGINAL_TITLE IN ALL_INFORMATION_ABOUT_FILM.ORIGINAL_TITLE%TYPE,
        POSTER IN ALL_INFORMATION_ABOUT_FILM.POSTER%TYPE,
        YEAR_OF_POSTING IN ALL_INFORMATION_ABOUT_FILM.YEAR_OF_POSTING%TYPE,
        COUNTRY IN ALL_INFORMATION_ABOUT_FILM.COUNTRY%TYPE,
        DESCRIPTION IN ALL_INFORMATION_ABOUT_FILM.DESCRIPTION%TYPE,
        RATING_IMDb IN ALL_INFORMATION_ABOUT_FILM.RATING_IMDb%TYPE,
        RATING_KP IN ALL_INFORMATION_ABOUT_FILM.RATING_KP%TYPE,
        BOX_OFFICE_RECEIPTS IN ALL_INFORMATION_ABOUT_FILM.BOX_OFFICE_RECEIPTS%TYPE,
        BUDGET IN ALL_INFORMATION_ABOUT_FILM.BUDGET%TYPE,
        AGE IN ALL_INFORMATION_ABOUT_FILM.AGE%TYPE,
        VIEWING_TIME IN ALL_INFORMATION_ABOUT_FILM.VIEWING_TIME%TYPE,
        GENRES IN ALL_INFORMATION_ABOUT_FILM.GENRES%TYPE,
        DIRECTORS IN ALL_INFORMATION_ABOUT_FILM.DIRECTORS%TYPE,
        ACTORS IN ALL_INFORMATION_ABOUT_FILM.ACTORS%TYPE,
        INTERESTING_FACT IN ALL_INFORMATION_ABOUT_FILM.INTERESTING_FACT%TYPE
        ) IS
    BEGIN
    --
        INSERT INTO ALL_INFORMATION_ABOUT_FILM VALUES(
            DEFAULT,TITLE,ORIGINAL_TITLE,POSTER,YEAR_OF_POSTING,COUNTRY,DESCRIPTION,RATING_IMDb,RATING_KP,BOX_OFFICE_RECEIPTS,BUDGET,AGE,VIEWING_TIME,GENRES,DIRECTORS,ACTORS,INTERESTING_FACT
        );
        COMMIT;
    END ADD_FILM;
    
    PROCEDURE DELETE_FILM_BY_ID(
        FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) IS
        BEGIN
            DELETE ALL_INFORMATION_ABOUT_FILM 
                WHERE ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID=FILM_ID;
            COMMIT;
        END DELETE_FILM_BY_ID;
        
    FUNCTION FIND_BY_ID(
         FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) RETURN SYS_REFCURSOR
    IS
        V_FILM_CURSOR SYS_REFCURSOR;
    BEGIN
        OPEN V_FILM_CURSOR FOR
            SELECT *
                FROM ALL_INFORMATION_ABOUT_FILM
                    WHERE ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID = FILM_ID;
        RETURN V_FILM_CURSOR;
    END FIND_BY_ID;
    
    FUNCTION GET_ALL_BY_ID(
         FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) RETURN SYS_REFCURSOR
    IS
        V_FILM_CURSOR SYS_REFCURSOR;
    BEGIN
        OPEN V_FILM_CURSOR FOR
            SELECT ALL_INFORMATION_ABOUT_FILM.*,USERS_REVIEWS_ON_MOVIE.USER_REVIEW_TEXT,USERS_REVIEWS_ON_MOVIE.DATE_OF_REVIEW,USER_PROFILE.LOGIN,USER_PROFILE.AVATAR,USER_PROFILE.USER_ROLE,USERS_REVIEWS_ON_MOVIE.USERS_REVIEWS_ON_MOVIE_ID
                FROM ALL_INFORMATION_ABOUT_FILM
                    FULL OUTER JOIN USERS_REVIEWS_ON_MOVIE
                        ON USERS_REVIEWS_ON_MOVIE.ALL_INFORMATION_ABOUT_FILM_ID=ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID
                    FULL OUTER JOIN USER_PROFILE
                        ON USER_PROFILE.USER_PROFILE_ID = USERS_REVIEWS_ON_MOVIE.USER_PROFILE_ID
                            WHERE ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID = FILM_ID;
        RETURN V_FILM_CURSOR;
    END GET_ALL_BY_ID;
    
    
    PROCEDURE UPDATE_FILM(
        FILM_ID IN ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID%TYPE,
        TITLE IN ALL_INFORMATION_ABOUT_FILM.TITLE%TYPE,
        ORIGINAL_TITLE IN ALL_INFORMATION_ABOUT_FILM.ORIGINAL_TITLE%TYPE,
        POSTER IN ALL_INFORMATION_ABOUT_FILM.POSTER%TYPE,
        YEAR_OF_POSTING IN ALL_INFORMATION_ABOUT_FILM.YEAR_OF_POSTING%TYPE,
        COUNTRY IN ALL_INFORMATION_ABOUT_FILM.COUNTRY%TYPE,
        DESCRIPTION IN ALL_INFORMATION_ABOUT_FILM.DESCRIPTION%TYPE,
        RATING_IMDb IN ALL_INFORMATION_ABOUT_FILM.RATING_IMDb%TYPE,
        RATING_KP IN ALL_INFORMATION_ABOUT_FILM.RATING_KP%TYPE,
        BOX_OFFICE_RECEIPTS IN ALL_INFORMATION_ABOUT_FILM.BOX_OFFICE_RECEIPTS%TYPE,
        BUDGET IN ALL_INFORMATION_ABOUT_FILM.BUDGET%TYPE,
        AGE IN ALL_INFORMATION_ABOUT_FILM.AGE%TYPE,
        VIEWING_TIME IN ALL_INFORMATION_ABOUT_FILM.VIEWING_TIME%TYPE,
        GENRES IN ALL_INFORMATION_ABOUT_FILM.GENRES%TYPE,
        DIRECTORS IN ALL_INFORMATION_ABOUT_FILM.DIRECTORS%TYPE,
        ACTORS IN ALL_INFORMATION_ABOUT_FILM.ACTORS%TYPE,
        INTERESTING_FACT IN ALL_INFORMATION_ABOUT_FILM.INTERESTING_FACT%TYPE
    ) IS
        BEGIN
            UPDATE ALL_INFORMATION_ABOUT_FILM
            SET
                ALL_INFORMATION_ABOUT_FILM.TITLE = UPDATE_FILM.TITLE,
                ALL_INFORMATION_ABOUT_FILM.ORIGINAL_TITLE = UPDATE_FILM.ORIGINAL_TITLE,
                ALL_INFORMATION_ABOUT_FILM.POSTER = UPDATE_FILM.POSTER,
                ALL_INFORMATION_ABOUT_FILM.YEAR_OF_POSTING = UPDATE_FILM.YEAR_OF_POSTING,
                ALL_INFORMATION_ABOUT_FILM.COUNTRY = UPDATE_FILM.COUNTRY,
                ALL_INFORMATION_ABOUT_FILM.DESCRIPTION = UPDATE_FILM.DESCRIPTION,
                ALL_INFORMATION_ABOUT_FILM.RATING_IMDb = UPDATE_FILM.RATING_IMDb,
                ALL_INFORMATION_ABOUT_FILM.RATING_KP = UPDATE_FILM.RATING_KP,
                ALL_INFORMATION_ABOUT_FILM.BOX_OFFICE_RECEIPTS = UPDATE_FILM.BOX_OFFICE_RECEIPTS,
                ALL_INFORMATION_ABOUT_FILM.BUDGET = UPDATE_FILM.BUDGET,
                ALL_INFORMATION_ABOUT_FILM.AGE = UPDATE_FILM.AGE,
                ALL_INFORMATION_ABOUT_FILM.VIEWING_TIME = UPDATE_FILM.VIEWING_TIME,
                ALL_INFORMATION_ABOUT_FILM.GENRES = UPDATE_FILM.GENRES,
                ALL_INFORMATION_ABOUT_FILM.DIRECTORS = UPDATE_FILM.DIRECTORS,
                ALL_INFORMATION_ABOUT_FILM.ACTORS = UPDATE_FILM.ACTORS,
                ALL_INFORMATION_ABOUT_FILM.INTERESTING_FACT = UPDATE_FILM.INTERESTING_FACT
            WHERE ALL_INFORMATION_ABOUT_FILM.ALL_INFORMATION_ABOUT_FILM_ID = UPDATE_FILM.FILM_ID;
            COMMIT;
        END UPDATE_FILM;
    
END ADMINFILMFUNCTIONS;
/