CREATE OR REPLACE PACKAGE SHAREDFUNCTIONS AS
    FUNCTION GET_ALL_DATA_FROM_TABLE(table_name IN VARCHAR2)
        RETURN SYS_REFCURSOR;
        
    PROCEDURE ADD_TO_SAVED(
        USER_PROFILE_ID IN USERS_REVIEWS_ON_MOVIE.USER_PROFILE_ID%TYPE,
        ALL_INFORMATION_ABOUT_FILM_ID IN USERS_REVIEWS_ON_MOVIE.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    );
    
    PROCEDURE ADD_TO_LIKED(
        USER_PROFILE_ID IN USERS_REVIEWS_ON_MOVIE.USER_PROFILE_ID%TYPE,
        ALL_INFORMATION_ABOUT_FILM_ID IN USERS_REVIEWS_ON_MOVIE.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    );
        
        

END SharedFunctions;
/

CREATE OR REPLACE PACKAGE BODY ADMIN.SHAREDFUNCTIONS AS
    FUNCTION GET_ALL_DATA_FROM_TABLE(table_name IN VARCHAR2)
        RETURN SYS_REFCURSOR
    IS
        RESULT SYS_REFCURSOR;
    BEGIN
        OPEN RESULT FOR 
            'SELECT * FROM '||table_name;
        RETURN RESULT;
    END;
    
    PROCEDURE ADD_TO_SAVED(
        USER_PROFILE_ID IN USERS_REVIEWS_ON_MOVIE.USER_PROFILE_ID%TYPE,
        ALL_INFORMATION_ABOUT_FILM_ID IN USERS_REVIEWS_ON_MOVIE.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) IS
    HERE NUMBER:=0;
    BEGIN
        SELECT COUNT(*) INTO HERE FROM USER_WATCH_LATER
            WHERE USER_WATCH_LATER.USER_PROFILE_ID =USER_PROFILE_ID 
                AND 
            USER_WATCH_LATER.ALL_INFORMATION_ABOUT_FILM =ALL_INFORMATION_ABOUT_FILM_ID;
            
        IF(HERE=1)THEN
            DELETE USER_WATCH_LATER 
                WHERE USER_WATCH_LATER.USER_PROFILE_ID =USER_PROFILE_ID AND USER_WATCH_LATER.ALL_INFORMATION_ABOUT_FILM =ALL_INFORMATION_ABOUT_FILM_ID;
            COMMIT;
        ELSE 
            INSERT INTO USER_WATCH_LATER VALUES(
                DEFAULT,ALL_INFORMATION_ABOUT_FILM_ID,USER_PROFILE_ID
            );
            COMMIT;
        END IF;       
    END ADD_TO_SAVED;
    
    PROCEDURE ADD_TO_LIKED(
        USER_PROFILE_ID IN USERS_REVIEWS_ON_MOVIE.USER_PROFILE_ID%TYPE,
        ALL_INFORMATION_ABOUT_FILM_ID IN USERS_REVIEWS_ON_MOVIE.ALL_INFORMATION_ABOUT_FILM_ID%TYPE
    ) IS
    HERE NUMBER:=0;
    BEGIN
        SELECT COUNT(*) INTO HERE FROM USER_LIKE
            WHERE USER_LIKE.USER_PROFILE_ID =USER_PROFILE_ID 
                AND 
            USER_LIKE.ALL_INFORMATION_ABOUT_FILM =ALL_INFORMATION_ABOUT_FILM_ID;
            
        IF(HERE=1)THEN
            DELETE USER_LIKE 
                WHERE USER_LIKE.USER_PROFILE_ID =ADD_TO_LIKED.USER_PROFILE_ID AND USER_LIKE.ALL_INFORMATION_ABOUT_FILM =ADD_TO_LIKED.ALL_INFORMATION_ABOUT_FILM_ID;
            COMMIT;
        ELSE 
            INSERT INTO USER_LIKE VALUES(
                DEFAULT,ALL_INFORMATION_ABOUT_FILM_ID,USER_PROFILE_ID
            );
            COMMIT;
        END IF;
    END ADD_TO_LIKED;
    
END SharedFunctions;
/