CREATE OR REPLACE PACKAGE ADMIN.SHAREDFUNCTIONS AS

    FUNCTION GET_ALL_DATA_FROM_TABLE(table_name IN VARCHAR2)
        RETURN SYS_REFCURSOR;

END SharedFunctions;
/

CREATE OR REPLACE PACKAGE BODY ADMIN.SHAREDFUNCTIONS AS
    FUNCTION GET_ALL_DATA_FROM_TABLE(table_name IN VARCHAR2)
        RETURN SYS_REFCURSOR
    IS
        RESULT SYS_REFCURSOR;
    BEGIN
        OPEN RESULT FOR 'SELECT * FROM '||table_name;
        RETURN RESULT;
    END;
END SharedFunctions;
/