CREATE OR REPLACE PACKAGE UserProfileFunctions AS
    PROCEDURE ADDUSER(
        FIRSTNAME IN USER_PROFILE.FIRSTNAME%TYPE,
        SECONDNAME IN USER_PROFILE.SECONDNAME%TYPE,
        EMAIL IN USER_PROFILE.EMAIL%TYPE,
        PASSWORD IN USER_PROFILE.PASSWORD%TYPE,
        USER_ROLE IN USER_PROFILE.USER_ROLE%TYPE
    );
    FUNCTION findByEMAIL(
        EMAILSS varchar
    ) RETURN SYS_REFCURSOR;
    
END UserProfileFunctions;
/

CREATE OR REPLACE PACKAGE BODY UserProfileFunctions AS
    PROCEDURE ADDUSER(
        FIRSTNAME IN USER_PROFILE.FIRSTNAME%TYPE,
        SECONDNAME IN USER_PROFILE.SECONDNAME%TYPE,
        EMAIL IN USER_PROFILE.EMAIL%TYPE,
        PASSWORD IN USER_PROFILE.PASSWORD%TYPE,
        USER_ROLE IN USER_PROFILE.USER_ROLE%TYPE
    ) IS
    BEGIN
       INSERT INTO USER_PROFILE VALUES(DEFAULT, FIRSTNAME, SECONDNAME, EMAIL, PASSWORD, USER_ROLE);
       COMMIT;
    END ADDUSER;
    
    FUNCTION findByEMAIL(
        EMAILSS varchar
    ) RETURN SYS_REFCURSOR
    IS
        V_USER_CURSOR SYS_REFCURSOR;
    BEGIN
        OPEN V_USER_CURSOR FOR
            SELECT *
                FROM USER_PROFILE
                    WHERE USER_PROFILE.EMAIL = EMAILSS;
        RETURN V_USER_CURSOR;
    END findByEMAIL;
    
END UserProfileFunctions;
/


